cmd_arch/arm/cpu/slsiap/s5p4418/mmu_asm.o := arm-linux-gcc -Wp,-MD,arch/arm/cpu/slsiap/s5p4418/.mmu_asm.o.d  -nostdinc -isystem /opt/FriendlyARM/toolchain/4.9.3/lib/gcc/arm-cortexa9-linux-gnueabihf/4.9.3/include -Iinclude  -I/root/uboot_nanopi2/arch/arm/include -D__KERNEL__ -DCONFIG_SYS_TEXT_BASE=0x42C00000  -D__ASSEMBLY__ -g      -DCONFIG_ARM -D__ARM__ -marm -mno-thumb-interwork  -mabi=aapcs-linux  -mword-relocations -mcpu=cortex-a9  -march=armv7-a  -ffunction-sections -fdata-sections -fno-common -ffixed-r9  -Wno-unused-but-set-variable -mno-unaligned-access -fno-short-enums -fstrict-aliasing  -I/root/uboot_nanopi2/arch/arm/cpu/slsiap/s5p4418/prototype/module -I/root/uboot_nanopi2/arch/arm/cpu/slsiap/s5p4418/prototype/base -I/root/uboot_nanopi2/arch/arm/include/asm/arch-s5p4418 -I/root/uboot_nanopi2/arch/arm/cpu/slsiap/common -I/root/uboot_nanopi2/arch/arm/cpu/slsiap/devices -I/root/uboot_nanopi2/board/s5p4418/common -D__LINUX__ -DNX_RELEASE -D__SUPPORT_MIO_UBOOT__ -D__SUPPORT_MIO_UBOOT_CHIP_S5P4418__ -I/root/uboot_nanopi2/board/s5p4418/nanopi2/include -pipe     -c -o arch/arm/cpu/slsiap/s5p4418/mmu_asm.o arch/arm/cpu/slsiap/s5p4418/mmu_asm.S

source_arch/arm/cpu/slsiap/s5p4418/mmu_asm.o := arch/arm/cpu/slsiap/s5p4418/mmu_asm.S

deps_arch/arm/cpu/slsiap/s5p4418/mmu_asm.o := \
    $(wildcard include/config/mmu/enable.h) \
    $(wildcard include/config/sys/init/sp/addr.h) \
  include/asm-offsets.h \
  include/generated/generic-asm-offsets.h \
  include/config.h \
    $(wildcard include/config/sys/arch.h) \
    $(wildcard include/config/sys/cpu.h) \
    $(wildcard include/config/sys/board.h) \
    $(wildcard include/config/sys/vendor.h) \
    $(wildcard include/config/sys/soc.h) \
    $(wildcard include/config/boarddir.h) \
  include/config_cmd_defaults.h \
    $(wildcard include/config/cmd/defaults/h/.h) \
    $(wildcard include/config/cmd/bootm.h) \
    $(wildcard include/config/cmd/crc32.h) \
    $(wildcard include/config/cmd/exportenv.h) \
    $(wildcard include/config/cmd/go.h) \
    $(wildcard include/config/cmd/importenv.h) \
  include/config_defaults.h \
    $(wildcard include/config/defaults/h/.h) \
    $(wildcard include/config/bootm/linux.h) \
    $(wildcard include/config/bootm/netbsd.h) \
    $(wildcard include/config/bootm/plan9.h) \
    $(wildcard include/config/bootm/rtems.h) \
    $(wildcard include/config/bootm/vxworks.h) \
    $(wildcard include/config/gzip.h) \
    $(wildcard include/config/zlib.h) \
    $(wildcard include/config/partitions.h) \
  include/configs/s5p4418_nanopi2.h \
    $(wildcard include/config/h//.h) \
    $(wildcard include/config/sys/ldscript.h) \
    $(wildcard include/config/sys/generic/board.h) \
    $(wildcard include/config/mach/s5p4418.h) \
    $(wildcard include/config/reloc/to/text/base.h) \
    $(wildcard include/config/sys/text/base.h) \
    $(wildcard include/config/mem/malloc/start.h) \
    $(wildcard include/config/mem/malloc/length.h) \
    $(wildcard include/config/lcd.h) \
    $(wildcard include/config/fb/addr.h) \
    $(wildcard include/config/bmp/addr.h) \
    $(wildcard include/config/mem/load/addr.h) \
    $(wildcard include/config/use/irq.h) \
    $(wildcard include/config/sys/hz.h) \
    $(wildcard include/config/sys/sdram/base.h) \
    $(wildcard include/config/sys/sdram/size.h) \
    $(wildcard include/config/nr/dram/banks.h) \
    $(wildcard include/config/sys/malloc/end.h) \
    $(wildcard include/config/sys/malloc/len.h) \
    $(wildcard include/config/sys/load/addr.h) \
    $(wildcard include/config/sys/memtest/start.h) \
    $(wildcard include/config/sys/memtest/end.h) \
    $(wildcard include/config/arch/cpu/init.h) \
    $(wildcard include/config/board/early/init/f.h) \
    $(wildcard include/config/board/late/init.h) \
    $(wildcard include/config/display/cpuinfo.h) \
    $(wildcard include/config/sys/dcache/off.h) \
    $(wildcard include/config/sys/icache/off.h) \
    $(wildcard include/config/arch/misc/init.h) \
    $(wildcard include/config/cmd/memory.h) \
    $(wildcard include/config/cmd/net.h) \
    $(wildcard include/config/cmd/run.h) \
    $(wildcard include/config/cmd/saveenv.h) \
    $(wildcard include/config/cmd/source.h) \
    $(wildcard include/config/cmd/bootd.h) \
    $(wildcard include/config/cmd/memtest.h) \
    $(wildcard include/config/bootdelay.h) \
    $(wildcard include/config/zero/bootdelay/check.h) \
    $(wildcard include/config/ethaddr.h) \
    $(wildcard include/config/netmask.h) \
    $(wildcard include/config/ipaddr.h) \
    $(wildcard include/config/serverip.h) \
    $(wildcard include/config/gatewayip.h) \
    $(wildcard include/config/bootfile.h) \
    $(wildcard include/config/loadcmd/ch0.h) \
    $(wildcard include/config/loadcmd/ch2.h) \
    $(wildcard include/config/loadcommand.h) \
    $(wildcard include/config/kernelimage.h) \
    $(wildcard include/config/bootcmd/ch2.h) \
    $(wildcard include/config/bootcommand.h) \
    $(wildcard include/config/sys/prompt.h) \
    $(wildcard include/config/sys/longhelp.h) \
    $(wildcard include/config/sys/cbsize.h) \
    $(wildcard include/config/sys/pbsize.h) \
    $(wildcard include/config/sys/maxargs.h) \
    $(wildcard include/config/sys/bargsize.h) \
    $(wildcard include/config/env/overwrite.h) \
    $(wildcard include/config/sys/hush/parser.h) \
    $(wildcard include/config/sys/prompt/hush/ps2.h) \
    $(wildcard include/config/cmd/bdi.h) \
    $(wildcard include/config/cmd/imi.h) \
    $(wildcard include/config/cmdline/editing.h) \
    $(wildcard include/config/cmdline/tag.h) \
    $(wildcard include/config/setup/memory/tags.h) \
    $(wildcard include/config/initrd/tag.h) \
    $(wildcard include/config/serial/tag.h) \
    $(wildcard include/config/revision/tag.h) \
    $(wildcard include/config/pl011/serial.h) \
    $(wildcard include/config/cons/index.h) \
    $(wildcard include/config/pl011/clock.h) \
    $(wildcard include/config/pl01x/ports.h) \
    $(wildcard include/config/baudrate.h) \
    $(wildcard include/config/sys/baudrate/table.h) \
    $(wildcard include/config/pl011/serial/flush/on/init.h) \
    $(wildcard include/config/driver/dm9000.h) \
    $(wildcard include/config/dm9000/base.h) \
    $(wildcard include/config/dm9000/debug.h) \
    $(wildcard include/config/cmd/nand.h) \
    $(wildcard include/config/nand/ftl.h) \
    $(wildcard include/config/nand/mtd.h) \
    $(wildcard include/config/env/is/in/nand.h) \
    $(wildcard include/config/sys/max/nand/device.h) \
    $(wildcard include/config/sys/nand/max/chips.h) \
    $(wildcard include/config/sys/nand/base.h) \
    $(wildcard include/config/env/offset.h) \
    $(wildcard include/config/env/size.h) \
    $(wildcard include/config/env/range.h) \
    $(wildcard include/config/sys/nand/onfi/detection.h) \
    $(wildcard include/config/cmd/nand/trimffs.h) \
    $(wildcard include/config/mtd/nand/nxp.h) \
    $(wildcard include/config/mtd/nand/ecc/bch.h) \
    $(wildcard include/config/mtd/nand/ecc/hw.h) \
    $(wildcard include/config/mtd/nand/verify/write.h) \
    $(wildcard include/config/mtd/nand/bmt/first/last.h) \
    $(wildcard include/config/cmd/update/nand.h) \
    $(wildcard include/config/bch.h) \
    $(wildcard include/config/nand/ecc/bch.h) \
    $(wildcard include/config/cmd/imls.h) \
    $(wildcard include/config/cmd/mtdparts.h) \
    $(wildcard include/config/mtd/device.h) \
    $(wildcard include/config/mtd/partitions.h) \
    $(wildcard include/config/mtd/debug.h) \
    $(wildcard include/config/mtd/debug/verbose.h) \
    $(wildcard include/config/sys/no/flash.h) \
    $(wildcard include/config/cmd/eeprom.h) \
    $(wildcard include/config/spi.h) \
    $(wildcard include/config/env/is/in/eeprom.h) \
    $(wildcard include/config/spi/module/0.h) \
    $(wildcard include/config/spi0/type.h) \
    $(wildcard include/config/eeprom/spi/module/num.h) \
    $(wildcard include/config/eeprom/erase/size.h) \
    $(wildcard include/config/eeprom/write/page/size.h) \
    $(wildcard include/config/eeprom/address/step.h) \
    $(wildcard include/config/spi/eeprom/write/protect.h) \
    $(wildcard include/config/spi/eeprom/wp/pad.h) \
    $(wildcard include/config/spi/eeprom/wp/alt.h) \
    $(wildcard include/config/cmd/spi/eeprom/update.h) \
    $(wildcard include/config/2stboot/offset.h) \
    $(wildcard include/config/2stboot/size.h) \
    $(wildcard include/config/uboot/offset.h) \
    $(wildcard include/config/uboot/size.h) \
    $(wildcard include/config/sys/def/eeprom/addr.h) \
    $(wildcard include/config/sys/i2c/fram.h) \
    $(wildcard include/config/spi/module/0/source/clock.h) \
    $(wildcard include/config/spi/module/0/clock.h) \
    $(wildcard include/config/spi/module/0/eeprom.h) \
    $(wildcard include/config/spi/module/1.h) \
    $(wildcard include/config/spi/module/1/source/clock.h) \
    $(wildcard include/config/spi/module/1/clock.h) \
    $(wildcard include/config/spi/module/1/eeprom.h) \
    $(wildcard include/config/spi1/type.h) \
    $(wildcard include/config/spi/module/2.h) \
    $(wildcard include/config/spi/module/2/source/clock.h) \
    $(wildcard include/config/spi/module/2/clock.h) \
    $(wildcard include/config/spi/module/2/eeprom.h) \
    $(wildcard include/config/spi2/type.h) \
    $(wildcard include/config/cmd/usb.h) \
    $(wildcard include/config/usb/ehci/synopsys.h) \
    $(wildcard include/config/usb/ehci/mode.h) \
    $(wildcard include/config/usb/hsic/mode.h) \
    $(wildcard include/config/usb/storage.h) \
    $(wildcard include/config/sys/usb/ehci/max/root/ports.h) \
    $(wildcard include/config/preboot.h) \
    $(wildcard include/config/usb/gadget.h) \
    $(wildcard include/config/nxp/usbdown.h) \
    $(wildcard include/config/nxp/dwc/otg.h) \
    $(wildcard include/config/nxp/dwc/otg/phy.h) \
    $(wildcard include/config/pmic.h) \
    $(wildcard include/config/cmd/i2c.h) \
    $(wildcard include/config/pmic/i2c.h) \
    $(wildcard include/config/pmic/i2c/bus.h) \
    $(wildcard include/config/pmic/charging/path/adp.h) \
    $(wildcard include/config/pmic/charging/path/ubc.h) \
    $(wildcard include/config/pmic/charging/path/adp/ubc.h) \
    $(wildcard include/config/pmic/charging/path/adp/ubc/linked.h) \
    $(wildcard include/config/power.h) \
    $(wildcard include/config/power/i2c.h) \
    $(wildcard include/config/power/battery.h) \
    $(wildcard include/config/power/fg.h) \
    $(wildcard include/config/power/muic.h) \
    $(wildcard include/config/pmic/axp228.h) \
    $(wildcard include/config/power/pmic/axp228.h) \
    $(wildcard include/config/power/battery/axp228.h) \
    $(wildcard include/config/power/muic/axp228.h) \
    $(wildcard include/config/power/fg/axp228.h) \
    $(wildcard include/config/sw/ubc/detect.h) \
    $(wildcard include/config/fastboot.h) \
    $(wildcard include/config/have/battery.h) \
    $(wildcard include/config/enable/init/voltage.h) \
    $(wildcard include/config/pmic/reg/dump.h) \
    $(wildcard include/config/pmic/voltage/check/with/charge.h) \
    $(wildcard include/config/power/battery/small.h) \
    $(wildcard include/config/bat/check.h) \
    $(wildcard include/config/nxp/rtc/use.h) \
    $(wildcard include/config/hard/i2c.h) \
    $(wildcard include/config/i2c/multi/bus.h) \
    $(wildcard include/config/i2c/gpio/mode.h) \
    $(wildcard include/config/sys/i2c/speed.h) \
    $(wildcard include/config/i2c0/nexell.h) \
    $(wildcard include/config/i2c0/no/stop.h) \
    $(wildcard include/config/i2c1/nexell.h) \
    $(wildcard include/config/i2c1/no/stop.h) \
    $(wildcard include/config/i2c2/nexell.h) \
    $(wildcard include/config/i2c2/no/stop.h) \
    $(wildcard include/config/i2c3/nexell.h) \
    $(wildcard include/config/i2c3/no/stop.h) \
    $(wildcard include/config/cmd/mmc.h) \
    $(wildcard include/config/env/is/in/mmc.h) \
    $(wildcard include/config/mmc.h) \
    $(wildcard include/config/generic/mmc.h) \
    $(wildcard include/config/mmc0/attach.h) \
    $(wildcard include/config/mmc1/attach.h) \
    $(wildcard include/config/mmc2/attach.h) \
    $(wildcard include/config/mmc0/clock.h) \
    $(wildcard include/config/mmc0/clk/delay.h) \
    $(wildcard include/config/mmc2/clock.h) \
    $(wildcard include/config/mmc2/clk/delay.h) \
    $(wildcard include/config/mmc2/bus/width.h) \
    $(wildcard include/config/mmc2/trans/mode.h) \
    $(wildcard include/config/dwmmc.h) \
    $(wildcard include/config/nxp/dwmmc.h) \
    $(wildcard include/config/mmc/partitions.h) \
    $(wildcard include/config/cmd/mmc/update.h) \
    $(wildcard include/config/sys/mmc/boot/dev.h) \
    $(wildcard include/config/gpiolib/nxp.h) \
    $(wildcard include/config/env/is/in/flash.h) \
    $(wildcard include/config/env/is/nowhere.h) \
    $(wildcard include/config/dos/partition.h) \
    $(wildcard include/config/cmd/fat.h) \
    $(wildcard include/config/fs/fat.h) \
    $(wildcard include/config/fat/write.h) \
    $(wildcard include/config/cmd/ext4.h) \
    $(wildcard include/config/cmd/ext4/write.h) \
    $(wildcard include/config/fs/ext4.h) \
    $(wildcard include/config/ext4/write.h) \
    $(wildcard include/config/cmd/ubifs.h) \
    $(wildcard include/config/rbtree.h) \
    $(wildcard include/config/cmd/ubi.h) \
    $(wildcard include/config/lzo.h) \
    $(wildcard include/config/ubifs/fs/debug.h) \
    $(wildcard include/config/ubifs/fs/debug/msg/lvl.h) \
    $(wildcard include/config/display/out.h) \
    $(wildcard include/config/logo/device/mmc.h) \
    $(wildcard include/config/logo/device/nand.h) \
    $(wildcard include/config/pwm.h) \
    $(wildcard include/config/display/out/rgb.h) \
    $(wildcard include/config/display/out/lvds.h) \
    $(wildcard include/config/display/out/hdmi.h) \
    $(wildcard include/config/logo/nexell.h) \
    $(wildcard include/config/cmd/logo/load.h) \
    $(wildcard include/config/cmd/logo/wallpapers.h) \
    $(wildcard include/config/cmd/logo/battery.h) \
    $(wildcard include/config/cmd/logo/update.h) \
    $(wildcard include/config/recovery/boot.h) \
    $(wildcard include/config/cmd/recovery/boot.h) \
    $(wildcard include/config/prototype/debug.h) \
  /root/uboot_nanopi2/arch/arm/include/asm/arch-s5p4418/platform.h \
  /root/uboot_nanopi2/arch/arm/include/asm/arch-s5p4418/s5p4418.h \
  /root/uboot_nanopi2/arch/arm/include/asm/arch-s5p4418/s5p4418_irq.h \
  /root/uboot_nanopi2/arch/arm/include/asm/config.h \
    $(wildcard include/config/h/.h) \
    $(wildcard include/config/sys/generic/global/data.h) \
    $(wildcard include/config/lmb.h) \
    $(wildcard include/config/sys/boot/ramdisk/high.h) \
    $(wildcard include/config/arm64.h) \
    $(wildcard include/config/phys/64bit.h) \
    $(wildcard include/config/static/rela.h) \
    $(wildcard include/config/fsl/lsch3.h) \
  include/config_fallbacks.h \
    $(wildcard include/config/fallbacks/h.h) \
    $(wildcard include/config/spl.h) \
    $(wildcard include/config/spl/pad/to.h) \
    $(wildcard include/config/spl/max/size.h) \
    $(wildcard include/config/cmd/ext2.h) \
    $(wildcard include/config/cmd/ide.h) \
    $(wildcard include/config/cmd/sata.h) \
    $(wildcard include/config/cmd/scsi.h) \
    $(wildcard include/config/cmd/part.h) \
    $(wildcard include/config/cmd/gpt.h) \
    $(wildcard include/config/systemace.h) \
    $(wildcard include/config/sandbox.h) \
    $(wildcard include/config/partition/uuids.h) \
    $(wildcard include/config/efi/partition.h) \
    $(wildcard include/config/random/uuid.h) \
    $(wildcard include/config/cmd/uuid.h) \
    $(wildcard include/config/bootp/pxe.h) \
    $(wildcard include/config/lib/uuid.h) \
    $(wildcard include/config/lib/rand.h) \
    $(wildcard include/config/lib/hw/rand.h) \
    $(wildcard include/config/api.h) \
    $(wildcard include/config/cmd/bmp.h) \
    $(wildcard include/config/fit/signature.h) \
    $(wildcard include/config/image/format/legacy.h) \
    $(wildcard include/config/disable/image/legacy.h) \
  include/config_uncmd_spl.h \
    $(wildcard include/config/uncmd/spl/h//.h) \
    $(wildcard include/config/spl/build.h) \
    $(wildcard include/config/cmd/cdp.h) \
    $(wildcard include/config/cmd/dhcp.h) \
    $(wildcard include/config/cmd/dns.h) \
    $(wildcard include/config/cmd/link/local.h) \
    $(wildcard include/config/cmd/nfs.h) \
    $(wildcard include/config/cmd/ping.h) \
    $(wildcard include/config/cmd/rarp.h) \
    $(wildcard include/config/cmd/sntp.h) \
    $(wildcard include/config/cmd/tftpput.h) \
    $(wildcard include/config/cmd/tftpsrv.h) \
  include/version.h \
    $(wildcard include/config/ident/string.h) \
  include/timestamp.h \
  include/generated/timestamp_autogenerated.h \
  include/generated/version_autogenerated.h \
  /root/uboot_nanopi2/arch/arm/include/asm/system.h \
  include/linux/linkage.h \
  /root/uboot_nanopi2/arch/arm/include/asm/linkage.h \

arch/arm/cpu/slsiap/s5p4418/mmu_asm.o: $(deps_arch/arm/cpu/slsiap/s5p4418/mmu_asm.o)

$(deps_arch/arm/cpu/slsiap/s5p4418/mmu_asm.o):
